version: '3'

services:
  mysql-docker-container:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Zappos
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - /data/mysql
  redis-container:
    image: redis:latest
    container_name: redis-container
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - my-net
  spring-boot-jpa-app:
    image: zapposrest:latest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
      - redis-container
    ports:
      - 8087:8080
    volumes:
      - /data/zappos
    networks:
      - my-net
networks:
  my-net:
    external: true

